
class OsbParserException(Exception): ...
class InvalidError(OsbParserException): ...
class ArgumentError(OsbParserException): ...


class IndentError(OsbParserException): ...


class InvalidSectionError(InvalidError): ...
class MultipleSectionError(OsbParserException): ...


class InvalidObjectTypeError(InvalidError): ...
class WrongArgumentCount(OsbParserException): ...
class WrongArgument(OsbParserException): ...
class SubCommandNotSupported(OsbParserException): ...
class InvalidEnum(InvalidError): ...
